# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  url: <%= ENV.fetch('DATABASE_URL') %>

development:
  <<: *default

test: &test
  <<: *default

production:
  <<: *default
